#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <grp.h>
#include <limits.h>
#include <locale.h>
#include <netdb.h>
#include <netinet/in.h>
#include <poll.h>
#include <pthread.h>
#include <pwd.h>
#include <sched.h>
#include <signal.h>
#include <stddef.h>
#include <sys/epoll.h>
#include <sys/mman.h>
#include <sys/resource.h>
#include <sys/select.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/statvfs.h>
#include <sys/time.h>
#include <sys/times.h>
#include <sys/types.h>
#include <sys/uio.h>
#include <sys/un.h>
#include <sys/utsname.h>
#include <termios.h>
#include <stdlib.h>
#include <time.h>
#include <unistd.h>
#include <sys/eventfd.h>

struct leanos_abi_fact {
    const char *name;
    unsigned long value;
};

static const struct leanos_abi_fact FACTS[] = {
    {"sizeof(struct stat)", (unsigned long)sizeof(struct stat)},
    {"alignof(struct stat)", (unsigned long)_Alignof(struct stat)},
    {"offsetof(struct stat,st_mode)", (unsigned long)offsetof(struct stat, st_mode)},
    {"offsetof(struct stat,st_size)", (unsigned long)offsetof(struct stat, st_size)},
    {"offsetof(struct stat,st_mtim)", (unsigned long)offsetof(struct stat, st_mtim)},
    {"offsetof(struct stat,st_atim)", (unsigned long)offsetof(struct stat, st_atim)},
    {"offsetof(struct stat,st_ctim)", (unsigned long)offsetof(struct stat, st_ctim)},
    {"offsetof(struct stat,st_nlink)", (unsigned long)offsetof(struct stat, st_nlink)},
    {"offsetof(struct stat,st_ino)", (unsigned long)offsetof(struct stat, st_ino)},
    {"offsetof(struct stat,st_dev)", (unsigned long)offsetof(struct stat, st_dev)},
    {"offsetof(struct stat,st_rdev)", (unsigned long)offsetof(struct stat, st_rdev)},
    {"offsetof(struct stat,st_uid)", (unsigned long)offsetof(struct stat, st_uid)},
    {"offsetof(struct stat,st_gid)", (unsigned long)offsetof(struct stat, st_gid)},
    {"offsetof(struct stat,st_blksize)", (unsigned long)offsetof(struct stat, st_blksize)},
    {"offsetof(struct stat,st_blocks)", (unsigned long)offsetof(struct stat, st_blocks)},
    {"sizeof(struct dirent)", (unsigned long)sizeof(struct dirent)},
    {"alignof(struct dirent)", (unsigned long)_Alignof(struct dirent)},
    {"offsetof(struct dirent,d_ino)", (unsigned long)offsetof(struct dirent, d_ino)},
    {"offsetof(struct dirent,d_type)", (unsigned long)offsetof(struct dirent, d_type)},
    {"offsetof(struct dirent,d_name)", (unsigned long)offsetof(struct dirent, d_name)},
    {"sizeof(struct sockaddr)", (unsigned long)sizeof(struct sockaddr)},
    {"alignof(struct sockaddr)", (unsigned long)_Alignof(struct sockaddr)},
    {"offsetof(struct sockaddr,sa_family)", (unsigned long)offsetof(struct sockaddr, sa_family)},
    {"offsetof(struct sockaddr,sa_data)", (unsigned long)offsetof(struct sockaddr, sa_data)},
    {"sizeof(struct in_addr)", (unsigned long)sizeof(struct in_addr)},
    {"alignof(struct in_addr)", (unsigned long)_Alignof(struct in_addr)},
    {"offsetof(struct in_addr,s_addr)", (unsigned long)offsetof(struct in_addr, s_addr)},
    {"sizeof(struct in6_addr)", (unsigned long)sizeof(struct in6_addr)},
    {"alignof(struct in6_addr)", (unsigned long)_Alignof(struct in6_addr)},
    {"offsetof(struct in6_addr,s6_addr)", (unsigned long)offsetof(struct in6_addr, s6_addr)},
    {"sizeof(struct sockaddr_in)", (unsigned long)sizeof(struct sockaddr_in)},
    {"alignof(struct sockaddr_in)", (unsigned long)_Alignof(struct sockaddr_in)},
    {"offsetof(struct sockaddr_in,sin_family)", (unsigned long)offsetof(struct sockaddr_in, sin_family)},
    {"offsetof(struct sockaddr_in,sin_port)", (unsigned long)offsetof(struct sockaddr_in, sin_port)},
    {"offsetof(struct sockaddr_in,sin_addr)", (unsigned long)offsetof(struct sockaddr_in, sin_addr)},
    {"offsetof(struct sockaddr_in,sin_zero)", (unsigned long)offsetof(struct sockaddr_in, sin_zero)},
    {"sizeof(struct sockaddr_in6)", (unsigned long)sizeof(struct sockaddr_in6)},
    {"alignof(struct sockaddr_in6)", (unsigned long)_Alignof(struct sockaddr_in6)},
    {"offsetof(struct sockaddr_in6,sin6_family)", (unsigned long)offsetof(struct sockaddr_in6, sin6_family)},
    {"offsetof(struct sockaddr_in6,sin6_port)", (unsigned long)offsetof(struct sockaddr_in6, sin6_port)},
    {"offsetof(struct sockaddr_in6,sin6_flowinfo)", (unsigned long)offsetof(struct sockaddr_in6, sin6_flowinfo)},
    {"offsetof(struct sockaddr_in6,sin6_addr)", (unsigned long)offsetof(struct sockaddr_in6, sin6_addr)},
    {"offsetof(struct sockaddr_in6,sin6_scope_id)", (unsigned long)offsetof(struct sockaddr_in6, sin6_scope_id)},
    {"sizeof(struct sockaddr_un)", (unsigned long)sizeof(struct sockaddr_un)},
    {"alignof(struct sockaddr_un)", (unsigned long)_Alignof(struct sockaddr_un)},
    {"offsetof(struct sockaddr_un,sun_family)", (unsigned long)offsetof(struct sockaddr_un, sun_family)},
    {"offsetof(struct sockaddr_un,sun_path)", (unsigned long)offsetof(struct sockaddr_un, sun_path)},
    {"sizeof(struct sockaddr_storage)", (unsigned long)sizeof(struct sockaddr_storage)},
    {"alignof(struct sockaddr_storage)", (unsigned long)_Alignof(struct sockaddr_storage)},
    {"offsetof(struct sockaddr_storage,ss_family)", (unsigned long)offsetof(struct sockaddr_storage, ss_family)},
    {"sizeof(struct msghdr)", (unsigned long)sizeof(struct msghdr)},
    {"alignof(struct msghdr)", (unsigned long)_Alignof(struct msghdr)},
    {"offsetof(struct msghdr,msg_name)", (unsigned long)offsetof(struct msghdr, msg_name)},
    {"offsetof(struct msghdr,msg_namelen)", (unsigned long)offsetof(struct msghdr, msg_namelen)},
    {"offsetof(struct msghdr,msg_iov)", (unsigned long)offsetof(struct msghdr, msg_iov)},
    {"offsetof(struct msghdr,msg_iovlen)", (unsigned long)offsetof(struct msghdr, msg_iovlen)},
    {"offsetof(struct msghdr,msg_control)", (unsigned long)offsetof(struct msghdr, msg_control)},
    {"offsetof(struct msghdr,msg_controllen)", (unsigned long)offsetof(struct msghdr, msg_controllen)},
    {"offsetof(struct msghdr,msg_flags)", (unsigned long)offsetof(struct msghdr, msg_flags)},
    {"sizeof(struct cmsghdr)", (unsigned long)sizeof(struct cmsghdr)},
    {"alignof(struct cmsghdr)", (unsigned long)_Alignof(struct cmsghdr)},
    {"offsetof(struct cmsghdr,cmsg_len)", (unsigned long)offsetof(struct cmsghdr, cmsg_len)},
    {"offsetof(struct cmsghdr,cmsg_level)", (unsigned long)offsetof(struct cmsghdr, cmsg_level)},
    {"offsetof(struct cmsghdr,cmsg_type)", (unsigned long)offsetof(struct cmsghdr, cmsg_type)},
    {"sizeof(struct addrinfo)", (unsigned long)sizeof(struct addrinfo)},
    {"alignof(struct addrinfo)", (unsigned long)_Alignof(struct addrinfo)},
    {"offsetof(struct addrinfo,ai_flags)", (unsigned long)offsetof(struct addrinfo, ai_flags)},
    {"offsetof(struct addrinfo,ai_family)", (unsigned long)offsetof(struct addrinfo, ai_family)},
    {"offsetof(struct addrinfo,ai_socktype)", (unsigned long)offsetof(struct addrinfo, ai_socktype)},
    {"offsetof(struct addrinfo,ai_protocol)", (unsigned long)offsetof(struct addrinfo, ai_protocol)},
    {"offsetof(struct addrinfo,ai_addrlen)", (unsigned long)offsetof(struct addrinfo, ai_addrlen)},
    {"offsetof(struct addrinfo,ai_addr)", (unsigned long)offsetof(struct addrinfo, ai_addr)},
    {"offsetof(struct addrinfo,ai_canonname)", (unsigned long)offsetof(struct addrinfo, ai_canonname)},
    {"offsetof(struct addrinfo,ai_next)", (unsigned long)offsetof(struct addrinfo, ai_next)},
    {"sizeof(struct ip_mreq)", (unsigned long)sizeof(struct ip_mreq)},
    {"alignof(struct ip_mreq)", (unsigned long)_Alignof(struct ip_mreq)},
    {"offsetof(struct ip_mreq,imr_multiaddr)", (unsigned long)offsetof(struct ip_mreq, imr_multiaddr)},
    {"offsetof(struct ip_mreq,imr_interface)", (unsigned long)offsetof(struct ip_mreq, imr_interface)},
    {"sizeof(struct passwd)", (unsigned long)sizeof(struct passwd)},
    {"alignof(struct passwd)", (unsigned long)_Alignof(struct passwd)},
    {"offsetof(struct passwd,pw_name)", (unsigned long)offsetof(struct passwd, pw_name)},
    {"offsetof(struct passwd,pw_passwd)", (unsigned long)offsetof(struct passwd, pw_passwd)},
    {"offsetof(struct passwd,pw_uid)", (unsigned long)offsetof(struct passwd, pw_uid)},
    {"offsetof(struct passwd,pw_gid)", (unsigned long)offsetof(struct passwd, pw_gid)},
    {"offsetof(struct passwd,pw_gecos)", (unsigned long)offsetof(struct passwd, pw_gecos)},
    {"offsetof(struct passwd,pw_dir)", (unsigned long)offsetof(struct passwd, pw_dir)},
    {"offsetof(struct passwd,pw_shell)", (unsigned long)offsetof(struct passwd, pw_shell)},
    {"sizeof(struct termios)", (unsigned long)sizeof(struct termios)},
    {"alignof(struct termios)", (unsigned long)_Alignof(struct termios)},
    {"offsetof(struct termios,c_iflag)", (unsigned long)offsetof(struct termios, c_iflag)},
    {"offsetof(struct termios,c_oflag)", (unsigned long)offsetof(struct termios, c_oflag)},
    {"offsetof(struct termios,c_cflag)", (unsigned long)offsetof(struct termios, c_cflag)},
    {"offsetof(struct termios,c_lflag)", (unsigned long)offsetof(struct termios, c_lflag)},
    {"offsetof(struct termios,c_cc)", (unsigned long)offsetof(struct termios, c_cc)},
    {"sizeof(struct flock)", (unsigned long)sizeof(struct flock)},
    {"alignof(struct flock)", (unsigned long)_Alignof(struct flock)},
    {"offsetof(struct flock,l_type)", (unsigned long)offsetof(struct flock, l_type)},
    {"offsetof(struct flock,l_whence)", (unsigned long)offsetof(struct flock, l_whence)},
    {"offsetof(struct flock,l_start)", (unsigned long)offsetof(struct flock, l_start)},
    {"offsetof(struct flock,l_len)", (unsigned long)offsetof(struct flock, l_len)},
    {"offsetof(struct flock,l_pid)", (unsigned long)offsetof(struct flock, l_pid)},
    {"sizeof(struct statvfs)", (unsigned long)sizeof(struct statvfs)},
    {"alignof(struct statvfs)", (unsigned long)_Alignof(struct statvfs)},
    {"offsetof(struct statvfs,f_bsize)", (unsigned long)offsetof(struct statvfs, f_bsize)},
    {"offsetof(struct statvfs,f_frsize)", (unsigned long)offsetof(struct statvfs, f_frsize)},
    {"offsetof(struct statvfs,f_blocks)", (unsigned long)offsetof(struct statvfs, f_blocks)},
    {"offsetof(struct statvfs,f_bfree)", (unsigned long)offsetof(struct statvfs, f_bfree)},
    {"offsetof(struct statvfs,f_bavail)", (unsigned long)offsetof(struct statvfs, f_bavail)},
    {"offsetof(struct statvfs,f_files)", (unsigned long)offsetof(struct statvfs, f_files)},
    {"offsetof(struct statvfs,f_ffree)", (unsigned long)offsetof(struct statvfs, f_ffree)},
    {"offsetof(struct statvfs,f_favail)", (unsigned long)offsetof(struct statvfs, f_favail)},
    {"offsetof(struct statvfs,f_fsid)", (unsigned long)offsetof(struct statvfs, f_fsid)},
    {"offsetof(struct statvfs,f_flag)", (unsigned long)offsetof(struct statvfs, f_flag)},
    {"offsetof(struct statvfs,f_namemax)", (unsigned long)offsetof(struct statvfs, f_namemax)},
    {"sizeof(struct utsname)", (unsigned long)sizeof(struct utsname)},
    {"alignof(struct utsname)", (unsigned long)_Alignof(struct utsname)},
    {"offsetof(struct utsname,sysname)", (unsigned long)offsetof(struct utsname, sysname)},
    {"offsetof(struct utsname,nodename)", (unsigned long)offsetof(struct utsname, nodename)},
    {"offsetof(struct utsname,release)", (unsigned long)offsetof(struct utsname, release)},
    {"offsetof(struct utsname,version)", (unsigned long)offsetof(struct utsname, version)},
    {"offsetof(struct utsname,machine)", (unsigned long)offsetof(struct utsname, machine)},
    {"sizeof(struct epoll_event)", (unsigned long)sizeof(struct epoll_event)},
    {"alignof(struct epoll_event)", (unsigned long)_Alignof(struct epoll_event)},
    {"offsetof(struct epoll_event,events)", (unsigned long)offsetof(struct epoll_event, events)},
    {"sizeof(struct itimerspec)", (unsigned long)sizeof(struct itimerspec)},
    {"alignof(struct itimerspec)", (unsigned long)_Alignof(struct itimerspec)},
    {"offsetof(struct itimerspec,it_interval)", (unsigned long)offsetof(struct itimerspec, it_interval)},
    {"offsetof(struct itimerspec,it_value)", (unsigned long)offsetof(struct itimerspec, it_value)},
    {"sizeof(struct timespec)", (unsigned long)sizeof(struct timespec)},
    {"alignof(struct timespec)", (unsigned long)_Alignof(struct timespec)},
    {"offsetof(struct timespec,tv_sec)", (unsigned long)offsetof(struct timespec, tv_sec)},
    {"offsetof(struct timespec,tv_nsec)", (unsigned long)offsetof(struct timespec, tv_nsec)},
    {"sizeof(struct timeval)", (unsigned long)sizeof(struct timeval)},
    {"alignof(struct timeval)", (unsigned long)_Alignof(struct timeval)},
    {"offsetof(struct timeval,tv_sec)", (unsigned long)offsetof(struct timeval, tv_sec)},
    {"offsetof(struct timeval,tv_usec)", (unsigned long)offsetof(struct timeval, tv_usec)},
    {"sizeof(struct iovec)", (unsigned long)sizeof(struct iovec)},
    {"alignof(struct iovec)", (unsigned long)_Alignof(struct iovec)},
    {"offsetof(struct iovec,iov_base)", (unsigned long)offsetof(struct iovec, iov_base)},
    {"offsetof(struct iovec,iov_len)", (unsigned long)offsetof(struct iovec, iov_len)},
    {"sizeof(struct pollfd)", (unsigned long)sizeof(struct pollfd)},
    {"alignof(struct pollfd)", (unsigned long)_Alignof(struct pollfd)},
    {"offsetof(struct pollfd,fd)", (unsigned long)offsetof(struct pollfd, fd)},
    {"offsetof(struct pollfd,events)", (unsigned long)offsetof(struct pollfd, events)},
    {"offsetof(struct pollfd,revents)", (unsigned long)offsetof(struct pollfd, revents)},
    {"sizeof(struct linger)", (unsigned long)sizeof(struct linger)},
    {"alignof(struct linger)", (unsigned long)_Alignof(struct linger)},
    {"offsetof(struct linger,l_onoff)", (unsigned long)offsetof(struct linger, l_onoff)},
    {"offsetof(struct linger,l_linger)", (unsigned long)offsetof(struct linger, l_linger)},
    {"sizeof(struct winsize)", (unsigned long)sizeof(struct winsize)},
    {"alignof(struct winsize)", (unsigned long)_Alignof(struct winsize)},
    {"offsetof(struct winsize,ws_row)", (unsigned long)offsetof(struct winsize, ws_row)},
    {"offsetof(struct winsize,ws_col)", (unsigned long)offsetof(struct winsize, ws_col)},
    {"offsetof(struct winsize,ws_xpixel)", (unsigned long)offsetof(struct winsize, ws_xpixel)},
    {"offsetof(struct winsize,ws_ypixel)", (unsigned long)offsetof(struct winsize, ws_ypixel)},
    {"sizeof(struct rlimit)", (unsigned long)sizeof(struct rlimit)},
    {"alignof(struct rlimit)", (unsigned long)_Alignof(struct rlimit)},
    {"offsetof(struct rlimit,rlim_cur)", (unsigned long)offsetof(struct rlimit, rlim_cur)},
    {"offsetof(struct rlimit,rlim_max)", (unsigned long)offsetof(struct rlimit, rlim_max)},
    {"sizeof(struct rusage)", (unsigned long)sizeof(struct rusage)},
    {"alignof(struct rusage)", (unsigned long)_Alignof(struct rusage)},
    {"offsetof(struct rusage,ru_utime)", (unsigned long)offsetof(struct rusage, ru_utime)},
    {"offsetof(struct rusage,ru_stime)", (unsigned long)offsetof(struct rusage, ru_stime)},
    {"offsetof(struct rusage,ru_maxrss)", (unsigned long)offsetof(struct rusage, ru_maxrss)},
    {"offsetof(struct rusage,ru_minflt)", (unsigned long)offsetof(struct rusage, ru_minflt)},
    {"offsetof(struct rusage,ru_majflt)", (unsigned long)offsetof(struct rusage, ru_majflt)},
    {"offsetof(struct rusage,ru_nvcsw)", (unsigned long)offsetof(struct rusage, ru_nvcsw)},
    {"offsetof(struct rusage,ru_nivcsw)", (unsigned long)offsetof(struct rusage, ru_nivcsw)},
    {"sizeof(struct sigaction)", (unsigned long)sizeof(struct sigaction)},
    {"alignof(struct sigaction)", (unsigned long)_Alignof(struct sigaction)},
    {"offsetof(struct sigaction,sa_mask)", (unsigned long)offsetof(struct sigaction, sa_mask)},
    {"offsetof(struct sigaction,sa_flags)", (unsigned long)offsetof(struct sigaction, sa_flags)},
    {"sizeof(siginfo_t)", (unsigned long)sizeof(siginfo_t)},
    {"alignof(siginfo_t)", (unsigned long)_Alignof(siginfo_t)},
    {"offsetof(siginfo_t,si_signo)", (unsigned long)offsetof(siginfo_t, si_signo)},
    {"offsetof(siginfo_t,si_code)", (unsigned long)offsetof(siginfo_t, si_code)},
    {"offsetof(siginfo_t,si_errno)", (unsigned long)offsetof(siginfo_t, si_errno)},
    {"offsetof(siginfo_t,si_pid)", (unsigned long)offsetof(siginfo_t, si_pid)},
    {"offsetof(siginfo_t,si_uid)", (unsigned long)offsetof(siginfo_t, si_uid)},
    {"offsetof(siginfo_t,si_address)", (unsigned long)offsetof(siginfo_t, si_address)},
    {"offsetof(siginfo_t,si_status)", (unsigned long)offsetof(siginfo_t, si_status)},
    {"offsetof(siginfo_t,si_band)", (unsigned long)offsetof(siginfo_t, si_band)},
    {"sizeof(struct tm)", (unsigned long)sizeof(struct tm)},
    {"alignof(struct tm)", (unsigned long)_Alignof(struct tm)},
    {"offsetof(struct tm,tm_sec)", (unsigned long)offsetof(struct tm, tm_sec)},
    {"offsetof(struct tm,tm_min)", (unsigned long)offsetof(struct tm, tm_min)},
    {"offsetof(struct tm,tm_hour)", (unsigned long)offsetof(struct tm, tm_hour)},
    {"offsetof(struct tm,tm_mday)", (unsigned long)offsetof(struct tm, tm_mday)},
    {"offsetof(struct tm,tm_mon)", (unsigned long)offsetof(struct tm, tm_mon)},
    {"offsetof(struct tm,tm_year)", (unsigned long)offsetof(struct tm, tm_year)},
    {"offsetof(struct tm,tm_wday)", (unsigned long)offsetof(struct tm, tm_wday)},
    {"offsetof(struct tm,tm_yday)", (unsigned long)offsetof(struct tm, tm_yday)},
    {"offsetof(struct tm,tm_isdst)", (unsigned long)offsetof(struct tm, tm_isdst)},
    {"offsetof(struct tm,tm_gmtoff)", (unsigned long)offsetof(struct tm, tm_gmtoff)},
    {"offsetof(struct tm,tm_zone)", (unsigned long)offsetof(struct tm, tm_zone)},
    {"sizeof(struct lconv)", (unsigned long)sizeof(struct lconv)},
    {"alignof(struct lconv)", (unsigned long)_Alignof(struct lconv)},
    {"offsetof(struct lconv,decimal_point)", (unsigned long)offsetof(struct lconv, decimal_point)},
    {"offsetof(struct lconv,thousands_sep)", (unsigned long)offsetof(struct lconv, thousands_sep)},
    {"offsetof(struct lconv,grouping)", (unsigned long)offsetof(struct lconv, grouping)},
    {"offsetof(struct lconv,int_frac_digits)", (unsigned long)offsetof(struct lconv, int_frac_digits)},
    {"offsetof(struct lconv,frac_digits)", (unsigned long)offsetof(struct lconv, frac_digits)},
    {"offsetof(struct lconv,n_sign_posn)", (unsigned long)offsetof(struct lconv, n_sign_posn)},
    {"sizeof(struct sched_param)", (unsigned long)sizeof(struct sched_param)},
    {"alignof(struct sched_param)", (unsigned long)_Alignof(struct sched_param)},
    {"offsetof(struct sched_param,sched_priority)", (unsigned long)offsetof(struct sched_param, sched_priority)},
    {"sizeof(pthread_mutex_t)", (unsigned long)sizeof(pthread_mutex_t)},
    {"alignof(pthread_mutex_t)", (unsigned long)_Alignof(pthread_mutex_t)},
    {"sizeof(pthread_cond_t)", (unsigned long)sizeof(pthread_cond_t)},
    {"alignof(pthread_cond_t)", (unsigned long)_Alignof(pthread_cond_t)},
    {"sizeof(pthread_rwlock_t)", (unsigned long)sizeof(pthread_rwlock_t)},
    {"alignof(pthread_rwlock_t)", (unsigned long)_Alignof(pthread_rwlock_t)},
    {"sizeof(pthread_attr_t)", (unsigned long)sizeof(pthread_attr_t)},
    {"alignof(pthread_attr_t)", (unsigned long)_Alignof(pthread_attr_t)},
    {"sizeof(pthread_mutexattr_t)", (unsigned long)sizeof(pthread_mutexattr_t)},
    {"alignof(pthread_mutexattr_t)", (unsigned long)_Alignof(pthread_mutexattr_t)},
    {"sizeof(pthread_condattr_t)", (unsigned long)sizeof(pthread_condattr_t)},
    {"alignof(pthread_condattr_t)", (unsigned long)_Alignof(pthread_condattr_t)},
    {"sizeof(pthread_t)", (unsigned long)sizeof(pthread_t)},
    {"alignof(pthread_t)", (unsigned long)_Alignof(pthread_t)},
    {"sizeof(pthread_key_t)", (unsigned long)sizeof(pthread_key_t)},
    {"alignof(pthread_key_t)", (unsigned long)_Alignof(pthread_key_t)},
    {"sizeof(fd_set)", (unsigned long)sizeof(fd_set)},
    {"alignof(fd_set)", (unsigned long)_Alignof(fd_set)},
    {"sizeof(off_t)", (unsigned long)sizeof(off_t)},
    {"alignof(off_t)", (unsigned long)_Alignof(off_t)},
    {"sizeof(mode_t)", (unsigned long)sizeof(mode_t)},
    {"alignof(mode_t)", (unsigned long)_Alignof(mode_t)},
    {"sizeof(ino_t)", (unsigned long)sizeof(ino_t)},
    {"alignof(ino_t)", (unsigned long)_Alignof(ino_t)},
    {"sizeof(dev_t)", (unsigned long)sizeof(dev_t)},
    {"alignof(dev_t)", (unsigned long)_Alignof(dev_t)},
    {"sizeof(nlink_t)", (unsigned long)sizeof(nlink_t)},
    {"alignof(nlink_t)", (unsigned long)_Alignof(nlink_t)},
    {"sizeof(blksize_t)", (unsigned long)sizeof(blksize_t)},
    {"alignof(blksize_t)", (unsigned long)_Alignof(blksize_t)},
    {"sizeof(blkcnt_t)", (unsigned long)sizeof(blkcnt_t)},
    {"alignof(blkcnt_t)", (unsigned long)_Alignof(blkcnt_t)},
    {"sizeof(fsblkcnt_t)", (unsigned long)sizeof(fsblkcnt_t)},
    {"alignof(fsblkcnt_t)", (unsigned long)_Alignof(fsblkcnt_t)},
    {"sizeof(fsfilcnt_t)", (unsigned long)sizeof(fsfilcnt_t)},
    {"alignof(fsfilcnt_t)", (unsigned long)_Alignof(fsfilcnt_t)},
    {"sizeof(time_t)", (unsigned long)sizeof(time_t)},
    {"alignof(time_t)", (unsigned long)_Alignof(time_t)},
    {"sizeof(suseconds_t)", (unsigned long)sizeof(suseconds_t)},
    {"alignof(suseconds_t)", (unsigned long)_Alignof(suseconds_t)},
    {"sizeof(clock_t)", (unsigned long)sizeof(clock_t)},
    {"alignof(clock_t)", (unsigned long)_Alignof(clock_t)},
    {"sizeof(clockid_t)", (unsigned long)sizeof(clockid_t)},
    {"alignof(clockid_t)", (unsigned long)_Alignof(clockid_t)},
    {"sizeof(socklen_t)", (unsigned long)sizeof(socklen_t)},
    {"alignof(socklen_t)", (unsigned long)_Alignof(socklen_t)},
    {"sizeof(sa_family_t)", (unsigned long)sizeof(sa_family_t)},
    {"alignof(sa_family_t)", (unsigned long)_Alignof(sa_family_t)},
    {"sizeof(sigset_t)", (unsigned long)sizeof(sigset_t)},
    {"alignof(sigset_t)", (unsigned long)_Alignof(sigset_t)},
    {"sizeof(nfds_t)", (unsigned long)sizeof(nfds_t)},
    {"alignof(nfds_t)", (unsigned long)_Alignof(nfds_t)},
    {"sizeof(rlim_t)", (unsigned long)sizeof(rlim_t)},
    {"alignof(rlim_t)", (unsigned long)_Alignof(rlim_t)},
    {"sizeof(tcflag_t)", (unsigned long)sizeof(tcflag_t)},
    {"alignof(tcflag_t)", (unsigned long)_Alignof(tcflag_t)},
    {"sizeof(cc_t)", (unsigned long)sizeof(cc_t)},
    {"alignof(cc_t)", (unsigned long)_Alignof(cc_t)},
    {"sizeof(pid_t)", (unsigned long)sizeof(pid_t)},
    {"alignof(pid_t)", (unsigned long)_Alignof(pid_t)},
    {"sizeof(uid_t)", (unsigned long)sizeof(uid_t)},
    {"alignof(uid_t)", (unsigned long)_Alignof(uid_t)},
    {"sizeof(gid_t)", (unsigned long)sizeof(gid_t)},
    {"alignof(gid_t)", (unsigned long)_Alignof(gid_t)},
    {"sizeof(ssize_t)", (unsigned long)sizeof(ssize_t)},
    {"alignof(ssize_t)", (unsigned long)_Alignof(ssize_t)},
    {"sizeof(in_addr_t)", (unsigned long)sizeof(in_addr_t)},
    {"alignof(in_addr_t)", (unsigned long)_Alignof(in_addr_t)},
    {"sizeof(in_port_t)", (unsigned long)sizeof(in_port_t)},
    {"alignof(in_port_t)", (unsigned long)_Alignof(in_port_t)},
    {"sizeof(eventfd_t)", (unsigned long)sizeof(eventfd_t)},
    {"alignof(eventfd_t)", (unsigned long)_Alignof(eventfd_t)},
    {"O_RDONLY", (unsigned long)(long long)(O_RDONLY)},
    {"O_ACCMODE", (unsigned long)(long long)(O_ACCMODE)},
    {"O_CLOEXEC", (unsigned long)(long long)(O_CLOEXEC)},
    {"F_DUPFD_CLOEXEC", (unsigned long)(long long)(F_DUPFD_CLOEXEC)},
    {"AT_FDCWD", (unsigned long)(long long)(AT_FDCWD)},
    {"S_IFMT", (unsigned long)(long long)(S_IFMT)},
    {"S_IFSOCK", (unsigned long)(long long)(S_IFSOCK)},
    {"S_IRWXU", (unsigned long)(long long)(S_IRWXU)},
    {"EPOLLET", (unsigned long)(long long)(EPOLLET)},
    {"EPOLLIN", (unsigned long)(long long)(EPOLLIN)},
    {"RLIM_INFINITY", (unsigned long)(long long)(RLIM_INFINITY)},
    {"INADDR_LOOPBACK", (unsigned long)(long long)(INADDR_LOOPBACK)},
    {"INADDR_NONE", (unsigned long)(long long)(INADDR_NONE)},
    {"UTIME_OMIT", (unsigned long)(long long)(UTIME_OMIT)},
    {"NCCS", (unsigned long)(long long)(NCCS)},
    {"EAI_SYSTEM", (unsigned long)(long long)(EAI_SYSTEM)},
    {"SEEK_END", (unsigned long)(long long)(SEEK_END)},
    {"MAP_ANONYMOUS", (unsigned long)(long long)(MAP_ANONYMOUS)},
    {"EWOULDBLOCK", (unsigned long)(long long)(EWOULDBLOCK)},
    {"ETXTBSY", (unsigned long)(long long)(ETXTBSY)},
    {"SOMAXCONN", (unsigned long)(long long)(SOMAXCONN)},
    {"PATH_MAX", (unsigned long)(long long)(PATH_MAX)},
    {"_SC_PAGESIZE", (unsigned long)(long long)(_SC_PAGESIZE)},
};

unsigned long leanos_abi_fact_count(void) {
    return sizeof(FACTS) / sizeof(FACTS[0]);
}

const struct leanos_abi_fact *leanos_abi_facts(void) {
    return FACTS;
}
