pub static FACTS: &[(&str, u64)] = &[
    ("sizeof(struct stat)", size_of::<libc::stat>() as u64),
    ("alignof(struct stat)", align_of::<libc::stat>() as u64),
    ("offsetof(struct stat,st_mode)", core::mem::offset_of!(libc::stat, st_mode) as u64),
    ("offsetof(struct stat,st_size)", core::mem::offset_of!(libc::stat, st_size) as u64),
    ("offsetof(struct stat,st_mtim)", core::mem::offset_of!(libc::stat, st_mtim) as u64),
    ("offsetof(struct stat,st_atim)", core::mem::offset_of!(libc::stat, st_atim) as u64),
    ("offsetof(struct stat,st_ctim)", core::mem::offset_of!(libc::stat, st_ctim) as u64),
    ("offsetof(struct stat,st_nlink)", core::mem::offset_of!(libc::stat, st_nlink) as u64),
    ("offsetof(struct stat,st_ino)", core::mem::offset_of!(libc::stat, st_ino) as u64),
    ("offsetof(struct stat,st_dev)", core::mem::offset_of!(libc::stat, st_dev) as u64),
    ("offsetof(struct stat,st_rdev)", core::mem::offset_of!(libc::stat, st_rdev) as u64),
    ("offsetof(struct stat,st_uid)", core::mem::offset_of!(libc::stat, st_uid) as u64),
    ("offsetof(struct stat,st_gid)", core::mem::offset_of!(libc::stat, st_gid) as u64),
    ("offsetof(struct stat,st_blksize)", core::mem::offset_of!(libc::stat, st_blksize) as u64),
    ("offsetof(struct stat,st_blocks)", core::mem::offset_of!(libc::stat, st_blocks) as u64),
    ("sizeof(struct dirent)", size_of::<libc::dirent>() as u64),
    ("alignof(struct dirent)", align_of::<libc::dirent>() as u64),
    ("offsetof(struct dirent,d_ino)", core::mem::offset_of!(libc::dirent, d_ino) as u64),
    ("offsetof(struct dirent,d_type)", core::mem::offset_of!(libc::dirent, d_type) as u64),
    ("offsetof(struct dirent,d_name)", core::mem::offset_of!(libc::dirent, d_name) as u64),
    ("sizeof(struct sockaddr)", size_of::<libc::sockaddr>() as u64),
    ("alignof(struct sockaddr)", align_of::<libc::sockaddr>() as u64),
    ("offsetof(struct sockaddr,sa_family)", core::mem::offset_of!(libc::sockaddr, sa_family) as u64),
    ("offsetof(struct sockaddr,sa_data)", core::mem::offset_of!(libc::sockaddr, sa_data) as u64),
    ("sizeof(struct in_addr)", size_of::<libc::in_addr>() as u64),
    ("alignof(struct in_addr)", align_of::<libc::in_addr>() as u64),
    ("offsetof(struct in_addr,s_addr)", core::mem::offset_of!(libc::in_addr, s_addr) as u64),
    ("sizeof(struct in6_addr)", size_of::<libc::in6_addr>() as u64),
    ("alignof(struct in6_addr)", align_of::<libc::in6_addr>() as u64),
    ("offsetof(struct in6_addr,s6_addr)", core::mem::offset_of!(libc::in6_addr, s6_addr) as u64),
    ("sizeof(struct sockaddr_in)", size_of::<libc::sockaddr_in>() as u64),
    ("alignof(struct sockaddr_in)", align_of::<libc::sockaddr_in>() as u64),
    ("offsetof(struct sockaddr_in,sin_family)", core::mem::offset_of!(libc::sockaddr_in, sin_family) as u64),
    ("offsetof(struct sockaddr_in,sin_port)", core::mem::offset_of!(libc::sockaddr_in, sin_port) as u64),
    ("offsetof(struct sockaddr_in,sin_addr)", core::mem::offset_of!(libc::sockaddr_in, sin_addr) as u64),
    ("offsetof(struct sockaddr_in,sin_zero)", core::mem::offset_of!(libc::sockaddr_in, sin_zero) as u64),
    ("sizeof(struct sockaddr_in6)", size_of::<libc::sockaddr_in6>() as u64),
    ("alignof(struct sockaddr_in6)", align_of::<libc::sockaddr_in6>() as u64),
    ("offsetof(struct sockaddr_in6,sin6_family)", core::mem::offset_of!(libc::sockaddr_in6, sin6_family) as u64),
    ("offsetof(struct sockaddr_in6,sin6_port)", core::mem::offset_of!(libc::sockaddr_in6, sin6_port) as u64),
    ("offsetof(struct sockaddr_in6,sin6_flowinfo)", core::mem::offset_of!(libc::sockaddr_in6, sin6_flowinfo) as u64),
    ("offsetof(struct sockaddr_in6,sin6_addr)", core::mem::offset_of!(libc::sockaddr_in6, sin6_addr) as u64),
    ("offsetof(struct sockaddr_in6,sin6_scope_id)", core::mem::offset_of!(libc::sockaddr_in6, sin6_scope_id) as u64),
    ("sizeof(struct sockaddr_un)", size_of::<libc::sockaddr_un>() as u64),
    ("alignof(struct sockaddr_un)", align_of::<libc::sockaddr_un>() as u64),
    ("offsetof(struct sockaddr_un,sun_family)", core::mem::offset_of!(libc::sockaddr_un, sun_family) as u64),
    ("offsetof(struct sockaddr_un,sun_path)", core::mem::offset_of!(libc::sockaddr_un, sun_path) as u64),
    ("sizeof(struct sockaddr_storage)", size_of::<libc::sockaddr_storage>() as u64),
    ("alignof(struct sockaddr_storage)", align_of::<libc::sockaddr_storage>() as u64),
    ("offsetof(struct sockaddr_storage,ss_family)", core::mem::offset_of!(libc::sockaddr_storage, ss_family) as u64),
    ("sizeof(struct msghdr)", size_of::<libc::msghdr>() as u64),
    ("alignof(struct msghdr)", align_of::<libc::msghdr>() as u64),
    ("offsetof(struct msghdr,msg_name)", core::mem::offset_of!(libc::msghdr, msg_name) as u64),
    ("offsetof(struct msghdr,msg_namelen)", core::mem::offset_of!(libc::msghdr, msg_namelen) as u64),
    ("offsetof(struct msghdr,msg_iov)", core::mem::offset_of!(libc::msghdr, msg_iov) as u64),
    ("offsetof(struct msghdr,msg_iovlen)", core::mem::offset_of!(libc::msghdr, msg_iovlen) as u64),
    ("offsetof(struct msghdr,msg_control)", core::mem::offset_of!(libc::msghdr, msg_control) as u64),
    ("offsetof(struct msghdr,msg_controllen)", core::mem::offset_of!(libc::msghdr, msg_controllen) as u64),
    ("offsetof(struct msghdr,msg_flags)", core::mem::offset_of!(libc::msghdr, msg_flags) as u64),
    ("sizeof(struct cmsghdr)", size_of::<libc::cmsghdr>() as u64),
    ("alignof(struct cmsghdr)", align_of::<libc::cmsghdr>() as u64),
    ("offsetof(struct cmsghdr,cmsg_len)", core::mem::offset_of!(libc::cmsghdr, cmsg_len) as u64),
    ("offsetof(struct cmsghdr,cmsg_level)", core::mem::offset_of!(libc::cmsghdr, cmsg_level) as u64),
    ("offsetof(struct cmsghdr,cmsg_type)", core::mem::offset_of!(libc::cmsghdr, cmsg_type) as u64),
    ("sizeof(struct addrinfo)", size_of::<libc::addrinfo>() as u64),
    ("alignof(struct addrinfo)", align_of::<libc::addrinfo>() as u64),
    ("offsetof(struct addrinfo,ai_flags)", core::mem::offset_of!(libc::addrinfo, ai_flags) as u64),
    ("offsetof(struct addrinfo,ai_family)", core::mem::offset_of!(libc::addrinfo, ai_family) as u64),
    ("offsetof(struct addrinfo,ai_socktype)", core::mem::offset_of!(libc::addrinfo, ai_socktype) as u64),
    ("offsetof(struct addrinfo,ai_protocol)", core::mem::offset_of!(libc::addrinfo, ai_protocol) as u64),
    ("offsetof(struct addrinfo,ai_addrlen)", core::mem::offset_of!(libc::addrinfo, ai_addrlen) as u64),
    ("offsetof(struct addrinfo,ai_addr)", core::mem::offset_of!(libc::addrinfo, ai_addr) as u64),
    ("offsetof(struct addrinfo,ai_canonname)", core::mem::offset_of!(libc::addrinfo, ai_canonname) as u64),
    ("offsetof(struct addrinfo,ai_next)", core::mem::offset_of!(libc::addrinfo, ai_next) as u64),
    ("sizeof(struct ip_mreq)", size_of::<libc::ip_mreq>() as u64),
    ("alignof(struct ip_mreq)", align_of::<libc::ip_mreq>() as u64),
    ("offsetof(struct ip_mreq,imr_multiaddr)", core::mem::offset_of!(libc::ip_mreq, imr_multiaddr) as u64),
    ("offsetof(struct ip_mreq,imr_interface)", core::mem::offset_of!(libc::ip_mreq, imr_interface) as u64),
    ("sizeof(struct passwd)", size_of::<libc::passwd>() as u64),
    ("alignof(struct passwd)", align_of::<libc::passwd>() as u64),
    ("offsetof(struct passwd,pw_name)", core::mem::offset_of!(libc::passwd, pw_name) as u64),
    ("offsetof(struct passwd,pw_passwd)", core::mem::offset_of!(libc::passwd, pw_passwd) as u64),
    ("offsetof(struct passwd,pw_uid)", core::mem::offset_of!(libc::passwd, pw_uid) as u64),
    ("offsetof(struct passwd,pw_gid)", core::mem::offset_of!(libc::passwd, pw_gid) as u64),
    ("offsetof(struct passwd,pw_gecos)", core::mem::offset_of!(libc::passwd, pw_gecos) as u64),
    ("offsetof(struct passwd,pw_dir)", core::mem::offset_of!(libc::passwd, pw_dir) as u64),
    ("offsetof(struct passwd,pw_shell)", core::mem::offset_of!(libc::passwd, pw_shell) as u64),
    ("sizeof(struct termios)", size_of::<libc::termios>() as u64),
    ("alignof(struct termios)", align_of::<libc::termios>() as u64),
    ("offsetof(struct termios,c_iflag)", core::mem::offset_of!(libc::termios, c_iflag) as u64),
    ("offsetof(struct termios,c_oflag)", core::mem::offset_of!(libc::termios, c_oflag) as u64),
    ("offsetof(struct termios,c_cflag)", core::mem::offset_of!(libc::termios, c_cflag) as u64),
    ("offsetof(struct termios,c_lflag)", core::mem::offset_of!(libc::termios, c_lflag) as u64),
    ("offsetof(struct termios,c_cc)", core::mem::offset_of!(libc::termios, c_cc) as u64),
    ("sizeof(struct flock)", size_of::<libc::flock>() as u64),
    ("alignof(struct flock)", align_of::<libc::flock>() as u64),
    ("offsetof(struct flock,l_type)", core::mem::offset_of!(libc::flock, l_type) as u64),
    ("offsetof(struct flock,l_whence)", core::mem::offset_of!(libc::flock, l_whence) as u64),
    ("offsetof(struct flock,l_start)", core::mem::offset_of!(libc::flock, l_start) as u64),
    ("offsetof(struct flock,l_len)", core::mem::offset_of!(libc::flock, l_len) as u64),
    ("offsetof(struct flock,l_pid)", core::mem::offset_of!(libc::flock, l_pid) as u64),
    ("sizeof(struct statvfs)", size_of::<libc::statvfs>() as u64),
    ("alignof(struct statvfs)", align_of::<libc::statvfs>() as u64),
    ("offsetof(struct statvfs,f_bsize)", core::mem::offset_of!(libc::statvfs, f_bsize) as u64),
    ("offsetof(struct statvfs,f_frsize)", core::mem::offset_of!(libc::statvfs, f_frsize) as u64),
    ("offsetof(struct statvfs,f_blocks)", core::mem::offset_of!(libc::statvfs, f_blocks) as u64),
    ("offsetof(struct statvfs,f_bfree)", core::mem::offset_of!(libc::statvfs, f_bfree) as u64),
    ("offsetof(struct statvfs,f_bavail)", core::mem::offset_of!(libc::statvfs, f_bavail) as u64),
    ("offsetof(struct statvfs,f_files)", core::mem::offset_of!(libc::statvfs, f_files) as u64),
    ("offsetof(struct statvfs,f_ffree)", core::mem::offset_of!(libc::statvfs, f_ffree) as u64),
    ("offsetof(struct statvfs,f_favail)", core::mem::offset_of!(libc::statvfs, f_favail) as u64),
    ("offsetof(struct statvfs,f_fsid)", core::mem::offset_of!(libc::statvfs, f_fsid) as u64),
    ("offsetof(struct statvfs,f_flag)", core::mem::offset_of!(libc::statvfs, f_flag) as u64),
    ("offsetof(struct statvfs,f_namemax)", core::mem::offset_of!(libc::statvfs, f_namemax) as u64),
    ("sizeof(struct utsname)", size_of::<libc::utsname>() as u64),
    ("alignof(struct utsname)", align_of::<libc::utsname>() as u64),
    ("offsetof(struct utsname,sysname)", core::mem::offset_of!(libc::utsname, sysname) as u64),
    ("offsetof(struct utsname,nodename)", core::mem::offset_of!(libc::utsname, nodename) as u64),
    ("offsetof(struct utsname,release)", core::mem::offset_of!(libc::utsname, release) as u64),
    ("offsetof(struct utsname,version)", core::mem::offset_of!(libc::utsname, version) as u64),
    ("offsetof(struct utsname,machine)", core::mem::offset_of!(libc::utsname, machine) as u64),
    ("sizeof(struct epoll_event)", size_of::<libc::epoll_event>() as u64),
    ("alignof(struct epoll_event)", align_of::<libc::epoll_event>() as u64),
    ("offsetof(struct epoll_event,events)", core::mem::offset_of!(libc::epoll_event, events) as u64),
    ("sizeof(struct itimerspec)", size_of::<libc::itimerspec>() as u64),
    ("alignof(struct itimerspec)", align_of::<libc::itimerspec>() as u64),
    ("offsetof(struct itimerspec,it_interval)", core::mem::offset_of!(libc::itimerspec, it_interval) as u64),
    ("offsetof(struct itimerspec,it_value)", core::mem::offset_of!(libc::itimerspec, it_value) as u64),
    ("sizeof(struct timespec)", size_of::<libc::timespec>() as u64),
    ("alignof(struct timespec)", align_of::<libc::timespec>() as u64),
    ("offsetof(struct timespec,tv_sec)", core::mem::offset_of!(libc::timespec, tv_sec) as u64),
    ("offsetof(struct timespec,tv_nsec)", core::mem::offset_of!(libc::timespec, tv_nsec) as u64),
    ("sizeof(struct timeval)", size_of::<libc::timeval>() as u64),
    ("alignof(struct timeval)", align_of::<libc::timeval>() as u64),
    ("offsetof(struct timeval,tv_sec)", core::mem::offset_of!(libc::timeval, tv_sec) as u64),
    ("offsetof(struct timeval,tv_usec)", core::mem::offset_of!(libc::timeval, tv_usec) as u64),
    ("sizeof(struct iovec)", size_of::<libc::iovec>() as u64),
    ("alignof(struct iovec)", align_of::<libc::iovec>() as u64),
    ("offsetof(struct iovec,iov_base)", core::mem::offset_of!(libc::iovec, iov_base) as u64),
    ("offsetof(struct iovec,iov_len)", core::mem::offset_of!(libc::iovec, iov_len) as u64),
    ("sizeof(struct pollfd)", size_of::<libc::pollfd>() as u64),
    ("alignof(struct pollfd)", align_of::<libc::pollfd>() as u64),
    ("offsetof(struct pollfd,fd)", core::mem::offset_of!(libc::pollfd, fd) as u64),
    ("offsetof(struct pollfd,events)", core::mem::offset_of!(libc::pollfd, events) as u64),
    ("offsetof(struct pollfd,revents)", core::mem::offset_of!(libc::pollfd, revents) as u64),
    ("sizeof(struct linger)", size_of::<libc::linger>() as u64),
    ("alignof(struct linger)", align_of::<libc::linger>() as u64),
    ("offsetof(struct linger,l_onoff)", core::mem::offset_of!(libc::linger, l_onoff) as u64),
    ("offsetof(struct linger,l_linger)", core::mem::offset_of!(libc::linger, l_linger) as u64),
    ("sizeof(struct winsize)", size_of::<libc::winsize>() as u64),
    ("alignof(struct winsize)", align_of::<libc::winsize>() as u64),
    ("offsetof(struct winsize,ws_row)", core::mem::offset_of!(libc::winsize, ws_row) as u64),
    ("offsetof(struct winsize,ws_col)", core::mem::offset_of!(libc::winsize, ws_col) as u64),
    ("offsetof(struct winsize,ws_xpixel)", core::mem::offset_of!(libc::winsize, ws_xpixel) as u64),
    ("offsetof(struct winsize,ws_ypixel)", core::mem::offset_of!(libc::winsize, ws_ypixel) as u64),
    ("sizeof(struct rlimit)", size_of::<libc::rlimit>() as u64),
    ("alignof(struct rlimit)", align_of::<libc::rlimit>() as u64),
    ("offsetof(struct rlimit,rlim_cur)", core::mem::offset_of!(libc::rlimit, rlim_cur) as u64),
    ("offsetof(struct rlimit,rlim_max)", core::mem::offset_of!(libc::rlimit, rlim_max) as u64),
    ("sizeof(struct rusage)", size_of::<libc::rusage>() as u64),
    ("alignof(struct rusage)", align_of::<libc::rusage>() as u64),
    ("offsetof(struct rusage,ru_utime)", core::mem::offset_of!(libc::rusage, ru_utime) as u64),
    ("offsetof(struct rusage,ru_stime)", core::mem::offset_of!(libc::rusage, ru_stime) as u64),
    ("offsetof(struct rusage,ru_maxrss)", core::mem::offset_of!(libc::rusage, ru_maxrss) as u64),
    ("offsetof(struct rusage,ru_minflt)", core::mem::offset_of!(libc::rusage, ru_minflt) as u64),
    ("offsetof(struct rusage,ru_majflt)", core::mem::offset_of!(libc::rusage, ru_majflt) as u64),
    ("offsetof(struct rusage,ru_nvcsw)", core::mem::offset_of!(libc::rusage, ru_nvcsw) as u64),
    ("offsetof(struct rusage,ru_nivcsw)", core::mem::offset_of!(libc::rusage, ru_nivcsw) as u64),
    ("sizeof(struct sigaction)", size_of::<libc::sigaction>() as u64),
    ("alignof(struct sigaction)", align_of::<libc::sigaction>() as u64),
    ("offsetof(struct sigaction,sa_mask)", core::mem::offset_of!(libc::sigaction, sa_mask) as u64),
    ("offsetof(struct sigaction,sa_flags)", core::mem::offset_of!(libc::sigaction, sa_flags) as u64),
    ("sizeof(siginfo_t)", size_of::<libc::siginfo_t>() as u64),
    ("alignof(siginfo_t)", align_of::<libc::siginfo_t>() as u64),
    ("offsetof(siginfo_t,si_signo)", core::mem::offset_of!(libc::siginfo_t, si_signo) as u64),
    ("offsetof(siginfo_t,si_code)", core::mem::offset_of!(libc::siginfo_t, si_code) as u64),
    ("offsetof(siginfo_t,si_errno)", core::mem::offset_of!(libc::siginfo_t, si_errno) as u64),
    ("offsetof(siginfo_t,si_pid)", core::mem::offset_of!(libc::siginfo_t, si_pid) as u64),
    ("offsetof(siginfo_t,si_uid)", core::mem::offset_of!(libc::siginfo_t, si_uid) as u64),
    ("offsetof(siginfo_t,si_addr)", core::mem::offset_of!(libc::siginfo_t, si_addr) as u64),
    ("offsetof(siginfo_t,si_status)", core::mem::offset_of!(libc::siginfo_t, si_status) as u64),
    ("offsetof(siginfo_t,si_band)", core::mem::offset_of!(libc::siginfo_t, si_band) as u64),
    ("sizeof(struct tm)", size_of::<libc::tm>() as u64),
    ("alignof(struct tm)", align_of::<libc::tm>() as u64),
    ("offsetof(struct tm,tm_sec)", core::mem::offset_of!(libc::tm, tm_sec) as u64),
    ("offsetof(struct tm,tm_min)", core::mem::offset_of!(libc::tm, tm_min) as u64),
    ("offsetof(struct tm,tm_hour)", core::mem::offset_of!(libc::tm, tm_hour) as u64),
    ("offsetof(struct tm,tm_mday)", core::mem::offset_of!(libc::tm, tm_mday) as u64),
    ("offsetof(struct tm,tm_mon)", core::mem::offset_of!(libc::tm, tm_mon) as u64),
    ("offsetof(struct tm,tm_year)", core::mem::offset_of!(libc::tm, tm_year) as u64),
    ("offsetof(struct tm,tm_wday)", core::mem::offset_of!(libc::tm, tm_wday) as u64),
    ("offsetof(struct tm,tm_yday)", core::mem::offset_of!(libc::tm, tm_yday) as u64),
    ("offsetof(struct tm,tm_isdst)", core::mem::offset_of!(libc::tm, tm_isdst) as u64),
    ("offsetof(struct tm,tm_gmtoff)", core::mem::offset_of!(libc::tm, tm_gmtoff) as u64),
    ("offsetof(struct tm,tm_zone)", core::mem::offset_of!(libc::tm, tm_zone) as u64),
    ("sizeof(struct lconv)", size_of::<libc::lconv>() as u64),
    ("alignof(struct lconv)", align_of::<libc::lconv>() as u64),
    ("offsetof(struct lconv,decimal_point)", core::mem::offset_of!(libc::lconv, decimal_point) as u64),
    ("offsetof(struct lconv,thousands_sep)", core::mem::offset_of!(libc::lconv, thousands_sep) as u64),
    ("offsetof(struct lconv,grouping)", core::mem::offset_of!(libc::lconv, grouping) as u64),
    ("offsetof(struct lconv,int_frac_digits)", core::mem::offset_of!(libc::lconv, int_frac_digits) as u64),
    ("offsetof(struct lconv,frac_digits)", core::mem::offset_of!(libc::lconv, frac_digits) as u64),
    ("offsetof(struct lconv,n_sign_posn)", core::mem::offset_of!(libc::lconv, n_sign_posn) as u64),
    ("sizeof(struct sched_param)", size_of::<libc::sched_param>() as u64),
    ("alignof(struct sched_param)", align_of::<libc::sched_param>() as u64),
    ("offsetof(struct sched_param,sched_priority)", core::mem::offset_of!(libc::sched_param, sched_priority) as u64),
    ("sizeof(pthread_mutex_t)", size_of::<libc::pthread_mutex_t>() as u64),
    ("alignof(pthread_mutex_t)", align_of::<libc::pthread_mutex_t>() as u64),
    ("sizeof(pthread_cond_t)", size_of::<libc::pthread_cond_t>() as u64),
    ("alignof(pthread_cond_t)", align_of::<libc::pthread_cond_t>() as u64),
    ("sizeof(pthread_rwlock_t)", size_of::<libc::pthread_rwlock_t>() as u64),
    ("alignof(pthread_rwlock_t)", align_of::<libc::pthread_rwlock_t>() as u64),
    ("sizeof(pthread_attr_t)", size_of::<libc::pthread_attr_t>() as u64),
    ("alignof(pthread_attr_t)", align_of::<libc::pthread_attr_t>() as u64),
    ("sizeof(pthread_mutexattr_t)", size_of::<libc::pthread_mutexattr_t>() as u64),
    ("alignof(pthread_mutexattr_t)", align_of::<libc::pthread_mutexattr_t>() as u64),
    ("sizeof(pthread_condattr_t)", size_of::<libc::pthread_condattr_t>() as u64),
    ("alignof(pthread_condattr_t)", align_of::<libc::pthread_condattr_t>() as u64),
    ("sizeof(pthread_t)", size_of::<libc::pthread_t>() as u64),
    ("alignof(pthread_t)", align_of::<libc::pthread_t>() as u64),
    ("sizeof(pthread_key_t)", size_of::<libc::pthread_key_t>() as u64),
    ("alignof(pthread_key_t)", align_of::<libc::pthread_key_t>() as u64),
    ("sizeof(fd_set)", size_of::<libc::fd_set>() as u64),
    ("alignof(fd_set)", align_of::<libc::fd_set>() as u64),
    ("sizeof(off_t)", size_of::<libc::off_t>() as u64),
    ("alignof(off_t)", align_of::<libc::off_t>() as u64),
    ("sizeof(mode_t)", size_of::<libc::mode_t>() as u64),
    ("alignof(mode_t)", align_of::<libc::mode_t>() as u64),
    ("sizeof(ino_t)", size_of::<libc::ino_t>() as u64),
    ("alignof(ino_t)", align_of::<libc::ino_t>() as u64),
    ("sizeof(dev_t)", size_of::<libc::dev_t>() as u64),
    ("alignof(dev_t)", align_of::<libc::dev_t>() as u64),
    ("sizeof(nlink_t)", size_of::<libc::nlink_t>() as u64),
    ("alignof(nlink_t)", align_of::<libc::nlink_t>() as u64),
    ("sizeof(blksize_t)", size_of::<libc::blksize_t>() as u64),
    ("alignof(blksize_t)", align_of::<libc::blksize_t>() as u64),
    ("sizeof(blkcnt_t)", size_of::<libc::blkcnt_t>() as u64),
    ("alignof(blkcnt_t)", align_of::<libc::blkcnt_t>() as u64),
    ("sizeof(fsblkcnt_t)", size_of::<libc::fsblkcnt_t>() as u64),
    ("alignof(fsblkcnt_t)", align_of::<libc::fsblkcnt_t>() as u64),
    ("sizeof(fsfilcnt_t)", size_of::<libc::fsfilcnt_t>() as u64),
    ("alignof(fsfilcnt_t)", align_of::<libc::fsfilcnt_t>() as u64),
    ("sizeof(time_t)", size_of::<libc::time_t>() as u64),
    ("alignof(time_t)", align_of::<libc::time_t>() as u64),
    ("sizeof(suseconds_t)", size_of::<libc::suseconds_t>() as u64),
    ("alignof(suseconds_t)", align_of::<libc::suseconds_t>() as u64),
    ("sizeof(clock_t)", size_of::<libc::clock_t>() as u64),
    ("alignof(clock_t)", align_of::<libc::clock_t>() as u64),
    ("sizeof(clockid_t)", size_of::<libc::clockid_t>() as u64),
    ("alignof(clockid_t)", align_of::<libc::clockid_t>() as u64),
    ("sizeof(socklen_t)", size_of::<libc::socklen_t>() as u64),
    ("alignof(socklen_t)", align_of::<libc::socklen_t>() as u64),
    ("sizeof(sa_family_t)", size_of::<libc::sa_family_t>() as u64),
    ("alignof(sa_family_t)", align_of::<libc::sa_family_t>() as u64),
    ("sizeof(sigset_t)", size_of::<libc::sigset_t>() as u64),
    ("alignof(sigset_t)", align_of::<libc::sigset_t>() as u64),
    ("sizeof(nfds_t)", size_of::<libc::nfds_t>() as u64),
    ("alignof(nfds_t)", align_of::<libc::nfds_t>() as u64),
    ("sizeof(rlim_t)", size_of::<libc::rlim_t>() as u64),
    ("alignof(rlim_t)", align_of::<libc::rlim_t>() as u64),
    ("sizeof(tcflag_t)", size_of::<libc::tcflag_t>() as u64),
    ("alignof(tcflag_t)", align_of::<libc::tcflag_t>() as u64),
    ("sizeof(cc_t)", size_of::<libc::cc_t>() as u64),
    ("alignof(cc_t)", align_of::<libc::cc_t>() as u64),
    ("sizeof(pid_t)", size_of::<libc::pid_t>() as u64),
    ("alignof(pid_t)", align_of::<libc::pid_t>() as u64),
    ("sizeof(uid_t)", size_of::<libc::uid_t>() as u64),
    ("alignof(uid_t)", align_of::<libc::uid_t>() as u64),
    ("sizeof(gid_t)", size_of::<libc::gid_t>() as u64),
    ("alignof(gid_t)", align_of::<libc::gid_t>() as u64),
    ("sizeof(ssize_t)", size_of::<libc::ssize_t>() as u64),
    ("alignof(ssize_t)", align_of::<libc::ssize_t>() as u64),
    ("sizeof(in_addr_t)", size_of::<libc::in_addr_t>() as u64),
    ("alignof(in_addr_t)", align_of::<libc::in_addr_t>() as u64),
    ("sizeof(in_port_t)", size_of::<libc::in_port_t>() as u64),
    ("alignof(in_port_t)", align_of::<libc::in_port_t>() as u64),
    ("sizeof(eventfd_t)", size_of::<libc::eventfd_t>() as u64),
    ("alignof(eventfd_t)", align_of::<libc::eventfd_t>() as u64),
    ("O_RDONLY", libc::O_RDONLY as i64 as u64),
    ("O_ACCMODE", libc::O_ACCMODE as i64 as u64),
    ("O_CLOEXEC", libc::O_CLOEXEC as i64 as u64),
    ("F_DUPFD_CLOEXEC", libc::F_DUPFD_CLOEXEC as i64 as u64),
    ("AT_FDCWD", libc::AT_FDCWD as i64 as u64),
    ("S_IFMT", libc::S_IFMT as u64),
    ("PTHREAD_STACK_MIN", libc::PTHREAD_STACK_MIN as u64),
    ("S_IFSOCK", libc::S_IFSOCK as u64),
    ("S_IRWXU", libc::S_IRWXU as u64),
    ("EPOLLET", libc::EPOLLET as u64),
    ("EPOLLIN", libc::EPOLLIN as u64),
    ("RLIM_INFINITY", libc::RLIM_INFINITY as u64),
    ("INADDR_LOOPBACK", libc::INADDR_LOOPBACK as u64),
    ("INADDR_NONE", libc::INADDR_NONE as u64),
    ("UTIME_OMIT", libc::UTIME_OMIT as i64 as u64),
    ("NCCS", libc::NCCS as u64),
    ("EAI_SYSTEM", libc::EAI_SYSTEM as i64 as u64),
    ("SEEK_END", libc::SEEK_END as i64 as u64),
    ("MAP_ANONYMOUS", libc::MAP_ANONYMOUS as i64 as u64),
    ("EWOULDBLOCK", libc::EWOULDBLOCK as i64 as u64),
    ("ETXTBSY", libc::ETXTBSY as i64 as u64),
    ("SOMAXCONN", libc::SOMAXCONN as i64 as u64),
    ("PATH_MAX", libc::PATH_MAX as i64 as u64),
    ("_SC_PAGESIZE", libc::_SC_PAGESIZE as i64 as u64),
];
