#!/usr/bin/env python3
"""Generate the tables strtold multiplies by.

Two tables, and the split between them is what decides the accuracy:

  EXACT[k]  = 10^k for 0 <= k <= 27, every one of them exactly representable
              in a 64-bit mantissa (10^k is exact while 5^k fits in 64 bits,
              and 5^27 does while 5^28 does not). A multiply by one of these
              rounds once and no more.

  BIG[q]    = 10^(28q), rounded once each. These are not exact - past 10^27
              nothing is - so each carries half an ulp of its own.

Any decimal exponent is 28q + r with 0 <= r < 28, so a conversion is at most
two multiplies: one by BIG[q] and one by EXACT[r]. That is where strtold's
claim of two units in the last place comes from, and it is why the tables are
shaped this way rather than as one table of every power.
"""

import os
import sys
from fractions import Fraction

MANTISSA_BITS = 64
EXACT_LIMIT = 27
STRIDE = 28
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# The long double exponent range, which is what decides how many BIG entries
# there have to be: 10^4932 is the largest finite power of ten.
MAX_DECIMAL_EXPONENT = 4932


def binary_exponent(value):
    exponent = value.numerator.bit_length() - value.denominator.bit_length()
    while Fraction(2) ** exponent > value:
        exponent -= 1
    while Fraction(2) ** (exponent + 1) <= value:
        exponent += 1
    return exponent


def round_to_long_double(value):
    value = Fraction(value)
    exponent = binary_exponent(value)
    step = Fraction(2) ** (exponent - MANTISSA_BITS + 1)
    units = int(value / step)
    if (value - units * step) * 2 >= step:
        units += 1
    return units * step


def hex_literal(value):
    exponent = binary_exponent(value)
    scaled = (value / Fraction(2) ** exponent) * Fraction(2) ** (MANTISSA_BITS - 1)
    if scaled.denominator != 1:
        raise ValueError("%s does not fit a %d-bit mantissa" % (value, MANTISSA_BITS))
    fraction = int(scaled) - (1 << (MANTISSA_BITS - 1))
    digits = ("%016x" % (fraction << 1)).rstrip("0") or "0"
    return "0x1.%sp%+dL" % (digits, exponent)


def main():
    if len(sys.argv) != 2:
        raise SystemExit("usage: gen-decimal-powers.py <output.c>")

    out = [
        "/* Generated by tools/gen-decimal-powers.py. Do not edit by hand: the",
        "   test regenerates this file and compares, so an edit here is a",
        "   failure rather than a change. */",
        "",
        '#include "decimal_powers.h"',
        "",
        "/* 10^k for k up to %d, each exactly representable - a multiply by one" % EXACT_LIMIT,
        "   of these rounds once and no more. */",
        "const long double DECIMAL_POWER_EXACT[DECIMAL_POWER_EXACT_COUNT] = {",
    ]
    for k in range(EXACT_LIMIT + 1):
        value = Fraction(10) ** k
        if value != round_to_long_double(value):
            raise SystemExit("10^%d is not exact - EXACT_LIMIT is wrong" % k)
        out.append("    %s," % hex_literal(value))
    out.append("};")
    out.append("")

    # Up to the last one this format can hold. 10^(28q) past the exponent
    # ceiling is an infinity, and an infinity in a table of scale factors is
    # a multiply that destroys the value it was meant to scale.
    count = 0
    while binary_exponent(round_to_long_double(Fraction(10) ** (STRIDE * count))) < 16384:
        count += 1
    out.append("/* 10^(%dq), rounded once each - half an ulp apiece, and past" % STRIDE)
    out.append("   10^%d there is no exact answer to round to. */" % EXACT_LIMIT)
    out.append("const long double DECIMAL_POWER_BIG[DECIMAL_POWER_BIG_COUNT] = {")
    for q in range(count):
        out.append("    %s," % hex_literal(round_to_long_double(Fraction(10) ** (STRIDE * q))))
    out.append("};")
    out.append("")

    header = [
        "#pragma once",
        "",
        "/* Generated alongside decimal_powers.c by tools/gen-decimal-powers.py. */",
        "",
        "#define DECIMAL_POWER_EXACT_LIMIT %d" % EXACT_LIMIT,
        "#define DECIMAL_POWER_EXACT_COUNT %d" % (EXACT_LIMIT + 1),
        "#define DECIMAL_POWER_STRIDE %d" % STRIDE,
        "#define DECIMAL_POWER_BIG_COUNT %d" % count,
        "",
        "extern const long double DECIMAL_POWER_EXACT[DECIMAL_POWER_EXACT_COUNT];",
        "extern const long double DECIMAL_POWER_BIG[DECIMAL_POWER_BIG_COUNT];",
        "",
    ]

    with open(sys.argv[1], "w") as handle:
        handle.write("\n".join(out))
    header_path = os.path.splitext(sys.argv[1])[0] + ".h"
    with open(header_path, "w") as handle:
        handle.write("\n".join(header))


if __name__ == "__main__":
    main()
