#!/usr/bin/env bash
# tools/install-python.sh - M99: put CPython on the disk.
#
# The install half of tools/build-python.sh, in the same shape as
# tools/install-native-toolchain.sh and for the same reasons: it skips
# with a message when the build has not happened (an image without
# Python is a valid image), it strips on the way in, and it puts the
# standard library on the filesystem as **.py source files** rather than
# freezing anything into the binary.
#
# That last part is M99's second bullet and it is worth stating plainly:
# M80 froze the library into the executable because M81's filesystem
# could not hold two thousand small files. M93's can - it is the
# milestone whose whole subject was a source tree - so the library goes
# on the disk the way it does everywhere else, and `import` reads it
# from there. An OS whose Python cannot see a .py file cannot run
# anybody's script.
set -uo pipefail

cd "$(dirname "$0")/.."
ROOT=$(pwd)

PYBUILD=build/python/build
IMAGE="${LEANOS_IMAGE:-build/os-image.bin}"
PUT=build/leanfs-put
CROSS_STRIP=build/toolchain/bin/x86_64-lean_os-strip
PY_VER=3.12.7
PY_MAJMIN=3.12

# What the interpreter is CALLED in the build tree, read out of the
# makefile configure generated rather than assumed.
#
# It is `python.exe` here, and not because anything is being built for
# Windows: CPython's configure sets BUILDEXE=.exe when the build
# directory is on a case-insensitive filesystem, because `python` and the
# `Python/` source directory would otherwise be the same name. macOS is
# case-insensitive by default, so this is the ordinary case on this
# machine and `$PYBUILD/python` - which is what this script looked for
# first - is a directory full of object files.
# ---- M99: asking the Makefile rather than reading it -------------------
#
# BUILDEXE below is a literal and a `sed` gets it. INSTSONAME and
# SHAREDMODS are not: they are written in make's own language -
# `libpython$(LDVERSION).so.1.0`, and LDVERSION is `$(VERSION)$(ABIFLAGS)`
# - so reading the line gives a string with variables still in it, and
# expanding them by hand is a small recursive interpreter that is wrong
# the day upstream adds a level.
#
# make already has one. This asks it, through a two-line makefile that
# includes CPython's own, which is the only way to get an answer that is
# right by construction rather than right today.
pymake_var() {
  ( cd "$PYBUILD" 2>/dev/null || exit 0
    printf 'include Makefile\n__leanos_print:\n\t@echo $(%s)\n' "$1" \
      > .leanos-print.mk
    make -s -f .leanos-print.mk __leanos_print 2>/dev/null
    rm -f .leanos-print.mk )
}

BUILDEXE=$(sed -n 's/^BUILDEXE=[[:space:]]*//p' "$PYBUILD/Makefile" 2>/dev/null)
PYBIN="$PYBUILD/python$BUILDEXE"

if [ ! -x "$PYBIN" ]; then
  echo "install-python: no python at $PYBIN - skipped."
  echo "          tools/build-python.sh builds it (M99); it is not part of \`make\`."
  exit 0
fi
[ -f "$IMAGE" ] || { echo "install-python: no image at $IMAGE - run make first" >&2; exit 1; }
[ -x "$PUT" ] || make -s leanfs-put || exit 1

STAGE=build/python/install
rm -rf "$STAGE"
mkdir -p "$STAGE"

cp "$PYBIN" "$STAGE/python3" || exit 1
"$CROSS_STRIP" "$STAGE/python3" || exit 1
"$PUT" "$IMAGE" "$STAGE/python3" /bin/python3 >/dev/null || exit 1
"$PUT" -s "$IMAGE" /bin/python3 /bin/python >/dev/null 2>&1 || true

# ---- M99's second increment: the interpreter library -------------------
#
# A shared build puts the interpreter in libpython3.12.so.1.0 and leaves
# python3 as a PIE that loads it. Installed under the SONAME the linker
# recorded rather than under the unversioned name - the .so symlink is a
# build-time convenience for `-lpython3.12` and means nothing at run
# time, which is the same reasoning M97 wrote down for libstdc++.so.6.
#
# /lib, because that is the first place ld-lean.so looks. Absent in a
# static build, which is not an error - LEANOS_PYTHON_LINK=static is a
# supported configuration and produces no library at all.
SONAME=$(pymake_var INSTSONAME)
if [ -n "$SONAME" ] && [ -f "$PYBUILD/$SONAME" ]; then
  cp "$PYBUILD/$SONAME" "$STAGE/$SONAME" || exit 1
  "$CROSS_STRIP" "$STAGE/$SONAME" || exit 1
  "$PUT" "$IMAGE" "$STAGE/$SONAME" "/lib/$SONAME" >/dev/null || exit 1
  echo "install-python: /lib/$SONAME ($(du -h "$STAGE/$SONAME" | cut -f1))"
fi

# The standard library. Everything CPython's own `make install` would
# put in $prefix/lib/python3.12, minus the parts that are meaningless
# here (the test suite is installed separately below, on purpose, so
# that an image can carry the library without carrying 40 MB of tests).
SRC="build/toolchain-src/Python-$PY_VER"
LIBSTAGE=build/python/lib
rm -rf "$LIBSTAGE"
mkdir -p "$LIBSTAGE"
( cd "$SRC/Lib" && tar cf - --exclude=test --exclude=idlelib --exclude=tkinter \
    --exclude=turtledemo --exclude='__pycache__' . ) | ( cd "$LIBSTAGE" && tar xf - )

# ---- two things the source tree does not have ------------------------
#
# _sysconfigdata__<platform>_.py is GENERATED by the build, not shipped -
# it is how `sysconfig` answers "what flags was this interpreter built
# with", and the standard library imports it by a name that contains the
# platform. Without it `import sysconfig` raises ModuleNotFoundError, and
# the first thing that hit here was CPython's OWN test runner, which asks
# for CFLAGS before it runs a single test.
SYSCONFIGDATA=$(find "$PYBUILD/build" -name '_sysconfigdata_*.py' | head -1)
[ -n "$SYSCONFIGDATA" ] || {
  echo "install-python: no _sysconfigdata_*.py under $PYBUILD/build - the build did not finish" >&2
  exit 1
}
cp "$SYSCONFIGDATA" "$LIBSTAGE/" || exit 1

# And lib-dynload, which is where a Python with SHARED extension modules
# keeps them.
#
# M99's first increment left this directory EMPTY and said why: a static
# interpreter cannot dlopen, so its C modules were linked in, and the
# directory existed only because getpath prints "Could not find platform
# dependent libraries <exec_prefix>" on every run when it is missing. The
# comment there ended "M99's extension-module bullet is what puts
# something in it." This is that bullet: fifty-eight shared objects, each
# opened by full path at the moment something imports it.
#
# Copied from $(SHAREDMODS) as configure computed it rather than from a
# glob, so that a module which failed to build is a missing file this
# script names rather than a module that quietly is not there. The test
# modules are the one exception, taken by glob because CPython's own
# regression suite imports them and nothing else does.
mkdir -p "$LIBSTAGE/lib-dynload"
SHAREDMODS=$(pymake_var SHAREDMODS)
NMODS=0
for m in $SHAREDMODS; do
  if [ ! -f "$PYBUILD/$m" ]; then
    echo "install-python: $m was configured but not built" >&2
    exit 1
  fi
  cp "$PYBUILD/$m" "$LIBSTAGE/lib-dynload/" || exit 1
  "$CROSS_STRIP" "$LIBSTAGE/lib-dynload/$(basename "$m")" || exit 1
  NMODS=$((NMODS + 1))
done
[ "$NMODS" = 0 ] || echo "install-python: $NMODS extension modules as shared objects in lib-dynload"

"$PUT" -r "$IMAGE" "$LIBSTAGE" /usr/lib/python$PY_MAJMIN >/dev/null || exit 1

COUNT=$(find "$LIBSTAGE" -name '*.py' | wc -l | tr -d ' ')
SIZE=$(du -sh "$LIBSTAGE" | cut -f1)
echo "install-python: python3 in /bin, and $COUNT .py files ($SIZE) under /usr/lib/python$PY_MAJMIN"

# The regression suite, which is M99's fourth bullet and the most
# valuable thing in this milestone: a test suite somebody else wrote,
# reporting its own failures. Installed under the library where
# `python3 -m test` expects it.
if [ "${LEANOS_PYTHON_TESTS:-1}" = "1" ]; then
  TESTSTAGE=build/python/tests
  rm -rf "$TESTSTAGE"
  mkdir -p "$TESTSTAGE"
  ( cd "$SRC/Lib/test" && tar cf - --exclude='__pycache__' . ) | \
    ( cd "$TESTSTAGE" && tar xf - )
  "$PUT" -r "$IMAGE" "$TESTSTAGE" /usr/lib/python$PY_MAJMIN/test >/dev/null || exit 1
  echo "install-python: and CPython's own regression suite under .../test"
fi

# The fixtures the [m99] boot self-test runs - M80's bar and the bar it
# said mattered more.
"$PUT" -r "$IMAGE" tests/python /tests/python >/dev/null || exit 1
