#!/usr/bin/env python3

import hashlib
import os
import shutil
import socket
import subprocess
import tempfile
import time

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IMAGE = os.environ.get("LEANOS_IMAGE") or os.path.join(REPO_ROOT, "build", "os-image.bin")
ARTIFACT_DIR = os.environ.get("LEANOS_INPUT_ARTIFACTS", "/tmp/leanos-input-failures")
OVMF_CODE = os.path.join(REPO_ROOT, "build", "ovmf", "OVMF_CODE.fd")
OVMF_VARS = os.path.join(REPO_ROOT, "build", "ovmf", "OVMF_VARS.fd")

BOOT_MARKER = "[init] PID 1 spawned"

MAX_STEP = 100

HOME_OVERSHOOT = 1200

CURSOR_COLOR = 0xFFFFFF
CURSOR_W = CURSOR_H = 8
_CURSOR_ROWS = (
    0b10000000,
    0b11000000,
    0b10100000,
    0b10010000,
    0b10001000,
    0b10111000,
    0b11000100,
    0b10000100,
)
CURSOR_PIXELS = tuple((x, y)
                      for y, bits in enumerate(_CURSOR_ROWS)
                      for x in range(CURSOR_W)
                      if bits & (0x80 >> x))

_CURSOR_SHAPE_ROWS = {
    "arrow": _CURSOR_ROWS,
    "horizontal": (0b00011000, 0b00111100, 0b01100110, 0b11000011,
                   0b11000011, 0b01100110, 0b00111100, 0b00011000),
    "vertical": (0b00011000, 0b00111100, 0b01111110, 0b00011000,
                 0b00011000, 0b01111110, 0b00111100, 0b00011000),
    "diag_nw_se": (0b11110000, 0b11000000, 0b10000000, 0b00000000,
                   0b00000000, 0b00000001, 0b00000011, 0b00001111),
    "diag_ne_sw": (0b00001111, 0b00000011, 0b00000001, 0b00000000,
                   0b00000000, 0b10000000, 0b11000000, 0b11110000),
    "move": (0b00011000, 0b00111100, 0b01011010, 0b11011011,
             0b11011011, 0b01011010, 0b00111100, 0b00011000),
}

CURSOR_SHAPES = {
    name: tuple((x, y)
                for y, bits in enumerate(rows)
                for x in range(CURSOR_W)
                if bits & (0x80 >> x))
    for name, rows in _CURSOR_SHAPE_ROWS.items()
}

class Ppm:

    def __init__(self, path):
        with open(path, "rb") as f:
            data = f.read()
        pos = 0

        def token():
            nonlocal pos
            while data[pos:pos + 1].isspace():
                pos += 1
            start = pos
            while pos < len(data) and not data[pos:pos + 1].isspace():
                pos += 1
            return data[start:pos]

        magic = token()
        if magic != b"P6":
            raise ValueError("screendump was not a P6 PPM: %r" % magic)
        self.width = int(token())
        self.height = int(token())
        maxval = int(token())
        if maxval != 255:
            raise ValueError("unexpected PPM maxval %d" % maxval)
        pos += 1
        self._pixels = data[pos:]

    def px(self, x, y):
        if not (0 <= x < self.width and 0 <= y < self.height):
            raise IndexError("(%d, %d) outside %dx%d screendump"
                             % (x, y, self.width, self.height))
        off = (y * self.width + x) * 3
        return (self._pixels[off] << 16) | (self._pixels[off + 1] << 8) | self._pixels[off + 2]

    def count_color(self, color, x0, y0, w, h):
        n = 0
        for y in range(y0, y0 + h):
            for x in range(x0, x0 + w):
                if self.px(x, y) == color:
                    n += 1
        return n

    def count_brighter(self, minimum_sum, x0, y0, w, h, ignore=None):
        n = 0
        for y in range(y0, y0 + h):
            for x in range(x0, x0 + w):
                c = self.px(x, y)
                if c == ignore:
                    continue
                if ((c >> 16) & 0xFF) + ((c >> 8) & 0xFF) + (c & 0xFF) >= minimum_sum:
                    n += 1
        return n

SNAPSHOT_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                            "build", "snapshot")
SNAPSHOT_TAG = "desktop"

NET_PAGE_PORT = 7778
NET_PAGE_URL = "http://10.0.2.100:%d/" % NET_PAGE_PORT
NET_PAGE_BLOCK = 0x2AA198
NET_PAGE_BYTES = 120 * 1024

def _write_if_changed(path, data, mode=0o644):
    try:
        with open(path, "rb") as f:
            if f.read() == data:
                os.chmod(path, mode)
                return
    except OSError:
        pass
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as f:
        f.write(data)
    os.chmod(path, mode)

_NET_PAGE_SERVER = b"""#!/bin/sh
# Generated by tools/qemu_input.py (M116) - a one-request HTTP server.
cr=$(printf '\\r')
while IFS= read -r line; do
  line=${line%"$cr"}
  [ -z "$line" ] && break
done
exec cat "$(dirname "$0")/page.http"
"""

def net_page_server():
    base = os.path.join(REPO_ROOT, "build", "input-fixtures")
    filler = []
    size = 0
    n = 0
    while size < NET_PAGE_BYTES:
        line = "<p>line %06d of the filler that has to arrive before the block does</p>\n" % n
        filler.append(line)
        size += len(line)
        n += 1
    body = ("<!DOCTYPE html>\n<html><head><title>M116</title><style>"
            "body{background:#fdf6e3;margin:0}"
            "#end{width:320px;height:120px;background:#2aa198}"
            "</style></head><body>\n"
            "<div style=\"display:none\">\n" + "".join(filler) + "</div>\n"
            "<div id=\"end\"></div></body></html>\n").encode()
    head = ("HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n"
            "Content-Length: %d\r\nConnection: close\r\n\r\n" % len(body)).encode()
    _write_if_changed(os.path.join(base, "page.http"), head + body)
    server = os.path.join(base, "serve.sh")
    _write_if_changed(server, _NET_PAGE_SERVER, 0o755)
    return server

def _qemu_disk_kind():
    return "ide" if os.environ.get("LEANOS_QEMU_DISK") == "ide" else "virtio"

def snapshot_key():
    h = hashlib.sha256()
    with open(IMAGE, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    h.update(("|%s|%s|%s|%s" % (_qemu_disk_kind(),
                                os.environ.get("QEMU_CPUS", "1"),
                                os.environ.get("LEANOS_QEMU_MEM", "4096"),
                                os.environ.get("LEANOS_QEMU_INPUT", "ps2"))).encode())
    return h.hexdigest()

def snapshot_paths(key=None):
    key = key or snapshot_key()
    base = os.path.join(SNAPSHOT_DIR, "desktop-%s" % key[:16])
    return base + ".qcow2", base + ".key"

def snapshot_is_valid(key=None):
    key = key or snapshot_key()
    qcow, meta = snapshot_paths(key)
    if not (os.path.exists(qcow) and os.path.exists(meta)):
        return False
    try:
        with open(meta) as f:
            return f.read().strip() == key
    except OSError:
        return False

def discard_snapshot(key=None):
    for path in snapshot_paths(key):
        try:
            os.unlink(path)
        except OSError:
            pass

def _clone(src, dst):
    for args in (["cp", "-c", src, dst], ["cp", "--reflink=auto", src, dst]):
        try:
            if subprocess.call(args, stdout=subprocess.DEVNULL,
                               stderr=subprocess.DEVNULL) == 0:
                return
        except OSError:
            pass
    shutil.copyfile(src, dst)

def build_snapshot(painted, boot_timeout=300, quiet=False):
    key = snapshot_key()
    qcow, meta = snapshot_paths(key)
    os.makedirs(SNAPSHOT_DIR, exist_ok=True)
    discard_snapshot(key)

    for name in os.listdir(SNAPSHOT_DIR):
        if name.startswith("desktop-") and not name.startswith("desktop-%s" % key[:16]):
            try:
                os.unlink(os.path.join(SNAPSHOT_DIR, name))
            except OSError:
                pass

    subprocess.check_call(
        ["qemu-img", "create", "-f", "qcow2", "-b", os.path.abspath(IMAGE),
         "-F", "raw", qcow],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

    said = ""
    m = Machine(quiet=quiet, boot_timeout=boot_timeout,
                snapshot_build=qcow)
    try:
        if not m.wait_for_marker(timeout=boot_timeout):
            raise RuntimeError("the snapshot guest never reached %r - see %s"
                               % (BOOT_MARKER, m.save_log("snapshot-boot-timeout")))
        deadline = time.time() + 60
        while time.time() < deadline:
            if painted(m.screenshot()):
                break
            time.sleep(0.5)
        else:
            raise RuntimeError("the snapshot guest never finished painting - see %s"
                               % m.save_log("snapshot-never-painted"))
        time.sleep(2.0)
        # M194: "painted" is the README icon's tile, and the Browser's is the
        # last one the desktop draws. Once the boot stopped waiting six
        # seconds for a keypress nobody sends (M193), the snapshot could be
        # taken with that icon still being drawn, and every test restored from
        # it saw the rest of the paint as a disturbance - which
        # launching_an_app_does_not_disturb_the_rest_of_the_screen duly
        # reported. A snapshot is of a desktop that has stopped drawing: two
        # screens a second apart, identical above the taskbar, whose clock
        # ticks.
        deadline = time.time() + 30
        previous = None
        while time.time() < deadline:
            shot = m.screenshot()
            above_taskbar = shot._pixels[:shot.width * 3 * min(shot.height, 720)]
            if above_taskbar == previous:
                break
            previous = above_taskbar
            time.sleep(1.0)
        said = m.savevm(SNAPSHOT_TAG, timeout=180)
    finally:
        m.kill()

    listing = subprocess.run(["qemu-img", "snapshot", "-l", qcow],
                             capture_output=True, text=True).stdout
    if SNAPSHOT_TAG not in listing:
        raise RuntimeError("savevm produced no snapshot in %s.\nqemu-img said: %s\n"
                           "the monitor said: %r"
                           % (qcow, listing.strip() or "(nothing)", said[-600:]))

    with open(meta, "w") as f:
        f.write(key + "\n")
    return qcow

class Machine:

    def __init__(self, extra_args=(), quiet=False, boot_timeout=None,
                 snapshot=None, snapshot_build=None, wired_network=True):
        if not os.path.exists(IMAGE):
            raise RuntimeError("no image at %s - run 'make' first" % IMAGE)
        if not os.path.exists(OVMF_CODE):
            raise RuntimeError("no OVMF at build/ovmf - run tools/build-ovmf.sh")

        self._dir = tempfile.mkdtemp(prefix="leanos-input-", dir="/tmp")
        self._mon_path = os.path.join(self._dir, "mon.sock")
        self.log_path = os.path.join(self._dir, "serial.log")
        self._quiet = quiet
        self.boot_timeout = boot_timeout

        self.restored = snapshot is not None
        vars_rt = os.path.join(self._dir, "OVMF_VARS.fd")
        shutil.copyfile(OVMF_VARS, vars_rt)
        if self.restored or snapshot_build:
            if snapshot_build:
                disk = snapshot_build
            else:
                disk = os.path.join(self._dir, "state.qcow2")
                _clone(snapshot, disk)
            disk_args = ["-drive", "if=none,id=disk0,format=qcow2,file=" + disk,
                         "-device", "virtio-blk-pci,drive=disk0"]
            if _qemu_disk_kind() == "ide":
                disk_args = ["-drive", "format=qcow2,file=" + disk]
            pflash_vars = ["-drive",
                           "if=pflash,format=raw,readonly=on,file=" + vars_rt]
            restore_args = [] if snapshot_build else ["-loadvm", SNAPSHOT_TAG]
        else:
            disk_args = (["-drive", "format=raw,snapshot=on,file=" + IMAGE]
                         if _qemu_disk_kind() == "ide" else
                         ["-drive", "if=none,id=disk0,format=raw,snapshot=on,file=" + IMAGE,
                          "-device", "virtio-blk-pci,drive=disk0"])
            pflash_vars = ["-drive", "if=pflash,format=raw,file=" + vars_rt]
            restore_args = []

        input_mode = os.environ.get("LEANOS_QEMU_INPUT", "ps2")
        if input_mode == "usb":
            machine_args = ["-machine", "pc,i8042=off"]
            usb_args = ["-device", "qemu-xhci,id=xhci0",
                        "-device", "usb-kbd,bus=xhci0.0",
                        "-device", "usb-mouse,bus=xhci0.0"]
        else:
            machine_args = []
            usb_args = []

        self._proc = subprocess.Popen([
            "qemu-system-x86_64",
            *machine_args,
            *usb_args,
            "-smp", os.environ.get("QEMU_CPUS", "1"),
            "-drive", "if=pflash,format=raw,readonly=on,file=" + OVMF_CODE,
            *pflash_vars,
            *disk_args,
            "-display", "none",
            "-m", os.environ.get("LEANOS_QEMU_MEM", "4096"),
            *(["-netdev", "user,id=net0,guestfwd=tcp:10.0.2.100:%d-cmd:%s"
                         % (NET_PAGE_PORT, net_page_server()),
               "-device", "rtl8139,netdev=net0"] if wired_network else ["-nic", "none"]),
            "-audiodev", "none,id=snd0", "-device", "AC97,audiodev=snd0",
            "-serial", "file:" + self.log_path,
            "-monitor", "unix:" + self._mon_path + ",server,nowait",
        ] + restore_args + list(extra_args),
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

        self._sock = None
        deadline = time.time() + 15
        while time.time() < deadline:
            try:
                s = socket.socket(socket.AF_UNIX)
                s.connect(self._mon_path)
                self._sock = s
                break
            except OSError:
                time.sleep(0.2)
        if self._sock is None:
            self.kill()
            raise RuntimeError("QEMU monitor socket never appeared")
        self._drain()

        self._shot_seq = 0
        self.cursor = None

    def _drain(self):
        self._sock.setblocking(False)
        try:
            while self._sock.recv(65536):
                pass
        except (BlockingIOError, socket.timeout):
            pass
        finally:
            self._sock.setblocking(True)

    def monitor(self, command, settle=0.0):
        self._sock.sendall(command.encode() + b"\n")
        self._drain()
        if settle:
            time.sleep(settle)

    def savevm(self, tag, timeout=180):
        self._drain()
        self._sock.sendall(("savevm %s\n" % tag).encode())
        deadline = time.time() + timeout
        seen = ""
        self._sock.settimeout(0.5)
        try:
            while time.time() < deadline:
                try:
                    chunk = self._sock.recv(65536)
                except socket.timeout:
                    continue
                except OSError:
                    break
                if not chunk:
                    break
                seen += chunk.decode(errors="replace")
                tail = seen.split(tag, 1)[-1]
                if "(qemu)" in tail:
                    return seen
        finally:
            self._sock.settimeout(None)
        raise RuntimeError("savevm did not finish within %ds; monitor said %r"
                           % (timeout, seen[-400:]))

    def read_log(self):
        try:
            with open(self.log_path, "r", errors="replace") as f:
                return f.read()
        except OSError:
            return ""

    def wait_for_marker(self, marker=BOOT_MARKER, timeout=90):
        deadline = time.time() + timeout
        while time.time() < deadline:
            if marker in self.read_log():
                return True
            time.sleep(0.5)
        return False

    def boot_to_desktop(self, settle=4.0, timeout=90):
        if self.restored:
            return
        if not self.wait_for_marker(timeout=timeout):
            raise RuntimeError("guest never reached %r - see %s"
                               % (BOOT_MARKER, self.save_log("boot-timeout")))
        time.sleep(settle)

    def sendkey(self, keys, hold_ms=None):
        if hold_ms is None:
            self.monitor("sendkey %s" % keys)
        else:
            self.monitor("sendkey %s %d" % (keys, hold_ms))

    def type_text(self, text):
        for ch in text:
            self.sendkey(_qemu_keyname(ch), None)
            time.sleep(0.03)

    def home(self):
        steps = (HOME_OVERSHOOT + MAX_STEP - 1) // MAX_STEP
        for _ in range(steps):
            self.monitor("mouse_move -%d -%d" % (MAX_STEP, MAX_STEP), settle=0.02)
        time.sleep(0.15)
        self.cursor = (0, 0)

    def _step_by(self, dx, dy):
        while dx or dy:
            sx = max(-MAX_STEP, min(MAX_STEP, dx))
            sy = max(-MAX_STEP, min(MAX_STEP, dy))
            self.monitor("mouse_move %d %d" % (sx, sy), settle=0.02)
            dx -= sx
            dy -= sy

    def find_cursor_shape(self, shot, near, radius=48):
        cx, cy = near
        best = None
        for oy in range(max(0, cy - radius), min(shot.height - CURSOR_H, cy + radius + 1)):
            for ox in range(max(0, cx - radius), min(shot.width - CURSOR_W, cx + radius + 1)):
                for name, pixels in CURSOR_SHAPES.items():
                    if all(shot.px(ox + px, oy + py) == CURSOR_COLOR for px, py in pixels):
                        key = (abs(ox - cx) + abs(oy - cy), -len(pixels))
                        if best is None or key < best[0]:
                            best = (key, ox, oy, name)
        return None if best is None else (best[1], best[2], best[3])

    def find_cursor(self, shot, near, radius=48):
        found = self.find_cursor_shape(shot, near, radius)
        return None if found is None else (found[0], found[1])

    def move_to(self, x, y, verify=True):
        if self.cursor != (0, 0):
            self.home()
        self._step_by(x, y)
        time.sleep(0.15)
        self.cursor = (x, y)
        if not verify:
            return
        for _attempt in range(3):
            found = self.find_cursor(self.screenshot(), (x, y))
            if found == (x, y):
                return
            if found is None:
                self.home()
                self._step_by(x, y)
            else:
                self._step_by(x - found[0], y - found[1])
            time.sleep(0.15)
        raise RuntimeError("could not place the pointer at (%d, %d)" % (x, y))

    BTN_LEFT = 1
    BTN_RIGHT = 2
    BTN_MIDDLE = 4

    def wheel(self, detents):
        step = 1 if detents > 0 else -1
        for _ in range(abs(detents)):
            self.monitor("mouse_move 0 0 %d" % step, settle=0.06)
        time.sleep(0.2)

    def button(self, mask):
        self.monitor("mouse_button %d" % mask, settle=0.03)

    def click(self, x=None, y=None, mask=BTN_LEFT, hold=0.04):
        if x is not None:
            self.move_to(x, y)
        self.button(mask)
        time.sleep(hold)
        self.button(0)
        time.sleep(0.04)

    def right_click(self, x=None, y=None):
        self.click(x, y, mask=self.BTN_RIGHT)

    def double_click(self, x=None, y=None, gap=0.05):
        if x is not None:
            self.move_to(x, y)
        self.click()
        time.sleep(gap)
        self.click()

    def press(self, x=None, y=None, mask=BTN_LEFT):
        if x is not None:
            self.move_to(x, y)
        self.button(mask)
        time.sleep(0.1)

    def move_held(self, x, y, steps=8):
        x0, y0 = self.cursor
        for i in range(1, steps + 1):
            nx = x0 + (x - x0) * i // steps
            ny = y0 + (y - y0) * i // steps
            self._step_by(nx - self.cursor[0], ny - self.cursor[1])
            self.cursor = (nx, ny)
            time.sleep(0.05)
        time.sleep(0.15)

    def release(self):
        self.button(0)
        time.sleep(0.25)

    def drag(self, x0, y0, x1, y1, steps=8):
        self.press(x0, y0)
        self.move_held(x1, y1, steps=steps)
        self.release()

    def screenshot(self):
        self._shot_seq += 1
        path = os.path.join(self._dir, "shot%03d.ppm" % self._shot_seq)
        self.monitor("screendump %s" % path, settle=0.0)
        deadline = time.time() + 10
        last = -1
        while time.time() < deadline:
            if os.path.exists(path):
                size = os.path.getsize(path)
                if size > 0 and size == last:
                    return Ppm(path)
                last = size
            time.sleep(0.1)
        raise RuntimeError("screendump never produced %s" % path)

    def wait_for_exit(self, timeout=30.0):
        deadline = time.time() + timeout
        started = time.time()
        while time.time() < deadline:
            if self._proc.poll() is not None:
                return time.time() - started
            time.sleep(0.25)
        return None

    @property
    def exit_status(self):
        return self._proc.poll()

    def kill(self):
        if self._sock is not None:
            try:
                self._sock.close()
            except OSError:
                pass
            self._sock = None
        if self._proc is not None:
            self._proc.kill()
            try:
                self._proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                pass
            self._proc = None

    def __enter__(self):
        return self

    def save_log(self, name):
        try:
            os.makedirs(ARTIFACT_DIR, exist_ok=True)
            dest = os.path.join(ARTIFACT_DIR, "%s-%d.log" % (name, os.getpid()))
            shutil.copyfile(self.log_path, dest)
            return dest
        except OSError:
            return self.log_path

    def __exit__(self, *_exc):
        self.kill()
        shutil.rmtree(self._dir, ignore_errors=True)

_SHIFTED = {
    "_": "shift-minus", ":": "shift-semicolon", "?": "shift-slash",
    "!": "shift-1", "@": "shift-2", "#": "shift-3", "$": "shift-4",
    "%": "shift-5", "^": "shift-6", "&": "shift-7", "*": "shift-8",
    "(": "shift-9", ")": "shift-0", "+": "shift-equal", "\"": "shift-apostrophe",
}
_NAMED = {
    " ": "spc", ".": "dot", ",": "comma", "-": "minus", "=": "equal",
    "/": "slash", ";": "semicolon", "'": "apostrophe", "\n": "ret",
}

def _qemu_keyname(ch):
    if ch in _SHIFTED:
        return _SHIFTED[ch]
    if ch in _NAMED:
        return _NAMED[ch]
    if ch.isupper():
        return "shift-" + ch.lower()
    return ch
